### ISSUE TITLE
Server are reported as down, but it is alive.

### ISSUE THREAD

**Issue by tuxmaster** [mozilla/http-observatory-website#63] opened 2016-08-31 09:14 UTC
There test server are reported as down, but it is alive.
Other site's can scan it without any problems.
How does the detection algorithms work?

**Comment by marumari** [comment] 2016-08-31 16:26
What site?  If you go to the front page and force a rescan, does that fix things?

**Comment by tuxmaster** [comment] 2016-09-01 05:25
No this will not fix it.
For example:  familie-büttner.de/xn--familie-bttner-osb.de

**Comment by marumari** [comment] 2016-09-01 14:17
Oh, I see.  This is actually a duplicate of bug #27.  If you fix the bad cert on your site, it should start working fine.

**Closed by marumari** 2016-09-01 14:17 UTC
