### ISSUE TITLE
"Cookies set without using the Secure flag, but transmission over HTTP prevented by HSTS"

### ISSUE THREAD

**Issue by acasademont** [mozilla/http-observatory-website#28] opened 2016-08-26 16:15 UTC
https://observatory.mozilla.org/analyze.html?host=ulabox.com

Both "ULBXSESS" and "ulabox" cookies are are sent with the "secure" flag (as can be seen in the "Raw Server Headers" section) so I'm not really sure what might be going on here.

Thanks!

**Comment by marumari** [comment] 2016-08-26 17:49
Hmm, that is very strange.  Thanks for letting me know.  I'll take a look into this as soon as I can and hopefully get things fixed for you.

**Comment by marumari** [comment] 2016-08-26 17:54
Looking at it, it appears that there is a cookie called "__cfduid" that is being set without the Secure flag.  I'm not sure why it's not showing up in the raw headers, but I think what's happening is that if multiple Set-Cookie headers appear than the code is only showing the most recently set one, and that's what I'm seeing:

on ulabox.com:
`Set-Cookie: __cfduid=d47044dd9a896df244af9cdf7489e38431472233921; expires=Sat, 26-Aug-17 17:52:01 GMT; path=/; domain=.ulabox.com; HttpOnly`

on www.ulabox.com:
`Set-Cookie: ulabox=9DfRBfTgLwnvQwAA1IwckC3tCu2p0hkzwSynW%2FhI5yuKKb3f0keeyvRehTKKGxQwS7uZ3AH5XtdwV0UkAak3nthfLqGO3%2B73fT53gC4dpJs%3D; expires=Wed, 26-Oct-2016 17:52:48 GMT; Max-Age=5270400; path=/; domain=.ulabox.com; secure; HttpOnly`

If you cut out the redirect, it does assess properly:
https://observatory.mozilla.org/analyze.html?host=www.ulabox.com

I'll keep looking to see if I can fix this.  Hopefully it's not something buried deep inside the requests library.  :)

**Comment by acasademont** [comment] 2016-08-26 18:00
Humm, it seems something related to our CloudFlare CDN. Thanks @marumari for the insight, it would be useful if we could display both sets of headers when there's a redirection!

**Comment by marumari** [comment] 2016-08-26 22:31
Totally!  I'll make sure to leave this bug open until I can figure out a solution to this particular problem.  Thanks again for reporting it!

**Comment by marumari** [comment] 2016-12-29 18:56
I'm going to close this bug, because it is a duplicate of this one:

https://github.com/mozilla/http-observatory/issues/121

Feel free to tag along there.  Hope to fix it soon!

**Closed by marumari** 2016-12-29 18:56 UTC
