### ISSUE TITLE
Test an url instead of a domain name

### ISSUE THREAD

**Issue by briner** [mozilla/http-observatory-website#71] opened 2016-10-13 13:55 UTC
Can we tell the observatory to test specifically an URL instead of a host. In our case, a lot of website are by a Central Identity Provider (in our caes: shibboleth) which works by doing a redirect to a forms and then redirect it to the webserver. Such schemes forces the user to insert his credential to access the resources.

We thought about creating a web page only for the purpose of testing it with http-observatory. But in that case, we need to provide an url.

**Comment by marumari** [comment] 2016-10-13 14:26
Do you mean specifically a URL with a path, like this:

https://foo.bar/baz/

Or just a plain URL, like https://foo.bar/

Thanks!

**Comment by briner** [comment] 2016-10-17 19:02
Hi, I mean https://foo.bar/baz/

Thanks

**Comment by marumari** [comment] 2016-10-17 19:09
Ah ha!  Got'cha!  This is actually a duplicate of:

https://github.com/mozilla/http-observatory/issues/76

Please go ahead and +1 it.  I do plan on getting this feature in sometime this quarter.  :)

Thanks!

**Closed by marumari** 2016-10-17 19:09 UTC
